export const ExclusionPeriod_Type = {
    "ja":{
        EXCLUSIONPERIOD_TYPE_10MIN:{
            name:"10分",
            value:10
        },
        EXCLUSIONPERIOD_TYPE_1H:{
            name:"1時間",
            value:60
        },
        EXCLUSIONPERIOD_TYPE_3H:{
            name:"3時間",
            value:60*3
        },
        EXCLUSIONPERIOD_TYPE_1DAY:{
            name:"1日",
            value:60*24
        },
        EXCLUSIONPERIOD_TYPE_UNLIMITED:{
            name:"無期限",
            value:0
        }
    },
    "en":{
        EXCLUSIONPERIOD_TYPE_10MIN:{
            name:"10min",
            value:10
        },
        EXCLUSIONPERIOD_TYPE_1H:{
            name:"1h",
            value:60
        },
        EXCLUSIONPERIOD_TYPE_3H:{
            name:"3h",
            value:60*3
        },
        EXCLUSIONPERIOD_TYPE_1DAY:{
            name:"1day",
            value:60*24
        },
        EXCLUSIONPERIOD_TYPE_UNLIMITED:{
            name:"unlimited",
            value:0
        }
    },
}